apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: monitoringdashboards.monitoring.kiali.io
  labels:
    app.kubernetes.io/name: {{ include "kiali-operator.name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app: {{ include "kiali-operator.name" . }}
    version: {{ .Chart.AppVersion }}
spec:
  group: monitoring.kiali.io
  names:
    kind: MonitoringDashboard
    listKind: MonitoringDashboardList
    plural: monitoringdashboards
    singular: monitoringdashboard
  scope: Namespaced
  version: v1alpha1
