apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "kiali-operator.name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app: {{ include "kiali-operator.name" . }}
    version: {{ .Chart.AppVersion }}
