apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kiali-operator.fullname" . }}
  labels:
    {{- include "kiali-operator.appName" . | indent 4 }}
    {{- include "kiali-operator.appVersion" . | indent 4 }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.operator.replicaCount }}
  selector:
    matchLabels:
      {{- include "kiali-operator.appName" . | indent 6}}
      {{- include "kiali-operator.appVersion" . | indent 6}}
  template:
    metadata:
      name: {{ include "kiali-operator.name" . }}
      labels:
      {{- include "kiali-operator.appName" . | indent 8}}
      {{- include "kiali-operator.appVersion" . | indent 8}}
    spec:
      serviceAccountName: {{ include "kiali-operator.name" . }}
      containers:
      - name: ansible
        command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
        image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
        imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
        volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
      - name: operator
        image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
        imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
        volumeMounts:
        - mountPath: /tmp/ansible-operator/runner
          name: runner
        env:
        - name: WATCH_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: {{ include "kiali-operator.fullname" . }}
        resources:
{{ toYaml .Values.operator.resources | indent 12 }}
    {{- with .Values.operator.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.operator.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.operator.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: runner
        emptyDir: {}
