apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kiali-operator.fullname" . }}
  labels:
    {{- include "kiali-operator.appName" . | indent 4 }}
    {{- include "kiali-operator.appVersion" . | indent 4 }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
subjects:
- kind: ServiceAccount
  name: {{ include "kiali-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kiali-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
