apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kiali-operator.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "kiali-operator.name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app: {{ include "kiali-operator.name" . }}
    version: {{ .Chart.AppVersion }}
subjects:
- kind: ServiceAccount
  name: {{ include "kiali-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "kiali-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
