{{- $ := . -}}
{{- range $instance := .Values.instances }}
{{- if $instance.auth }}
apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: {{ $instance.namespace }}
  labels:
    {{- include "kiali-operator.appName" $ | indent 4 }}
    {{- include "kiali-operator.appVersion" $ | indent 4 }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
type: Opaque
data:
  username: {{ default "admin" $instance.auth.username | b64enc | quote }}
  {{ if $instance.auth.passphrase }}
  passphrase: {{ $instance.auth.passphrase | b64enc | quote }}
  {{ else }}
  passphrase: {{ randAlphaNum 30 | b64enc | quote }}
  {{ end }}
{{ end }}
{{ end }}
