apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kiali-operator.fullname" . }}
  labels:
    {{- include "kiali-operator.appName" . | indent 4 }}
    {{- include "kiali-operator.appVersion" . | indent 4 }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
