apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "kubereplay.fullname" . }}-initializer
  labels:
    app: {{ template "kubereplay.name" . }}
    chart: {{ template "kubereplay.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "kubereplay.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "kubereplay.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.initializer.image.repository }}:{{ .Values.initializer.image.tag }}"
          args:
          - "--initializer-name"
          - {{ template "kubereplay.fullname" . }}.initializer.lwolf.org
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
