apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
  name: {{ template "kubereplay.fullname" . }}
initializers:
  - name: {{ template "kubereplay.fullname" . }}.initializer.lwolf.org
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - "*"
        resources:
          - deployments
