apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "kubereplay.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kubereplay.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
    - pods
    - deployments
    - events
    - configmaps
    - persistentvolumes
    - persistentvolumeclaims
  verbs:
    - "*"
- apiGroups:
  - kubereplay.lwolf.org
  resources:
  - harvesters
  - refineries
  verbs:
  - "*"