apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "viktoria-metrics.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "viktoria-metrics.name" . }}
    helm.sh/chart: {{ include "viktoria-metrics.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "viktoria-metrics.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "viktoria-metrics.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -httpListenAddr=:8080
            - -storageDataPath={{ .Values.persistence.storageDataPath }}
            {{- if .Values.loggerLevel -}}
            - -loggerLevel={{ .Values.loggerLevel }}
            {{- end }}
            {{- if .Values.maxQueryDuration -}}
            - -maxQueryDuration={{ .Values.maxQueryDuration }}
            {{- end }}
            {{- if .Values.precisionBits -}}
            - -precisionBits={{ .Values.precisionBits }}
            {{- end }}
            {{- if .Values.retentionPeriod -}}
            - -retentionPeriod={{ .Values.retentionPeriod }}
            {{- end }}
            {{- if and (.Values.tls.enabled) (.Values.tls.tlsCertFile) (.Values.tls.tlsKeyFile) }}
            - -tls={{ .Values.tls.enabled }}
            - -tlsCertFile={{ .Values.tls.tlsCertFile }}
            - -tlsKeyFile={{ .Values.tls.tlsKeyFile }}
            {{- end }}
          volumeMounts:
          - mountPath: {{ .Values.persistence.storageDataPath }}
            name: data
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "viktoria-metrics.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{ end }}
